version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        HTTP_PROXY: ${http_proxy}
        HTTPS_PROXY: ${https_proxy}

    ports:
      - "12000:3000"

    command: ["npm", "start"]
    